dotnet-core/Bulky/BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using Bulky.DataAccess;
using Bulky.DataAccess.Repository;
using Bulky.DataAccess.IRepository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace BulkyBookWeb.Controllers;
[Area("Admin")]
public class CompanyController : Controller
{
    private readonly IUnitOfWork unitOfWork;


    public CompanyController(IUnitOfWork _unitOfWork)
    {
        unitOfWork = _unitOfWork;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Upsert(int? id)
    {
        Company company = new();
        if (id != null && id != 0)
        {
            company = unitOfWork.Company.GetFirstOrDefaultNull(c => c.Id == id);
        }
        return View(company);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Upsert(Company company, IFormFile? file)
    {
        if (ModelState.IsValid)
        {
            if (company.Id == 0)
            {
                unitOfWork.Company.Add(company);
                TempData["success"] = "Company created successfully";
            }
            else
            {
                unitOfWork.Company.Update(company);
                TempData["success"] = "Company updated successfully";
            }
            unitOfWork.Save();
            return RedirectToAction("Index");
        }
        return View(company);
    }


    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var companies = unitOfWork.Company.GetAll();
        return Json(new { data = companies });
    }

    [HttpDelete, ActionName("Delete")]
    public IActionResult ApiDelete(int? id)
    {
        var company = unitOfWork.Company.GetFirstOrDefaultNull(c => c.Id == id);
        if (company == null)
        {
            return Json(new { success = false, message = "Error when deleting" });
        } else
        {
            unitOfWork.Company.Remove(company);
            unitOfWork.Save();
            return Json(new { success = true, message = "Delete successful" });
        }
    }

    #endregion
}

dotnet-core/Bulky/BulkyWeb/Areas/Admin/Views/Company/Index.cshtml
@{
    ViewData["Title"] = "Index company";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Company List</h2>
        </div>
        <div class="col-6 text-end ">
            <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-lg"></i>
                Create new company
            </a>
        </div>
    </div>
    <table id="table-data" class="table table-bordered table-striped" style="width: 100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Street address</th>
                <th>City</th>
                <th>State</th>
                <th>Postal code</th>
                <th>Phone number</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>

@section Scripts{
    <script src="~/js/company.js"></script>
}

dotnet-core/Bulky/BulkyWeb/Areas/Admin/Views/Company/Upsert.cshtml
@model Company
@{
    ViewData["Title"] = "Product";
}

<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <div class="border p-3 mt-4 row">
        <input asp-for="Id" hidden />
        <div class="row pb-2">
            <h2 class="text-primary">
                @(Model.Id != 0 ? "Edit" : "Create") product
            </h2>
            <hr />
        </div>
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="StreetAddress"></label>
            <input asp-for="StreetAddress" class="form-control" />
            <span asp-validation-for="StreetAddress" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="City"></label>
            <input asp-for="City" class="form-control" />
            <span asp-validation-for="City" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="State"></label>
            <input asp-for="State" class="form-control" />
            <span asp-validation-for="State" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PostalCode"></label>
            <input asp-for="PostalCode" class="form-control" />
            <span asp-validation-for="PostalCode" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PhoneNumber"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="col-12">
            @if (Model.Id != 0)
            {
                <button type="submit" class="btn btn-primary" style="width: 150px">Update</button>
            }
            else
            {
                <button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
            }
            <a asp-controller="Company" asp-action="Index" class="btn btn-secondary" style="width: 150px">
                Back to list
            </a>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}