dotnet-core/Bulky/BulkyWeb/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Bulky.DataAccess.Data;
using Bulky.Models;
using Bulky.DataAccess.IRepository;
using Microsoft.Extensions.Hosting;

namespace BulkyWeb.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Category> categories = _unitOfWork.Category.GetAll().OrderBy(category => category.DisplayOrder).ToList();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The display order can't exactly match the name");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();
                TempData["success"] = "Category created successfully!";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category? category = _unitOfWork.Category.GetFirstOrDefaultNull(c => c.Id == id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        public IActionResult Update(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "The display order can't exactly match the name");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();
                TempData["success"] = "Category updated successfully!";
                return RedirectToAction("Index");
            }
            return View();
        }

        //[HttpGet]
        //public IActionResult Delete(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    Category? category = _unitOfWork.Category.GetFirstOrDefaultNull(c => c.Id == id);
        //    if (category == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(category);
        //}

        //[HttpPost, ActionName("Delete")]
        //public IActionResult DeleteHandle(int? id)
        //{
        //    Category? category = _unitOfWork.Category.GetFirstOrDefaultNull(c => c.Id == id);
        //    if (category == null)
        //    {
        //        return NotFound();
        //    }
        //    _unitOfWork.Category.Remove(category);
        //    _unitOfWork.Save();
        //    TempData["success"] = "Category deleted successfully!";
        //    return RedirectToAction("Index");
        //}

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var categoryList = _unitOfWork.Category
                .GetAll()
                .OrderBy(category => category.DisplayOrder);
            return Json(new { data = categoryList });
        }

        [HttpDelete, ActionName("Delete")]
        public IActionResult ApiDelete(int? id)
        {
            Category? category = _unitOfWork.Category.GetFirstOrDefaultNull(c => c.Id == id);
            if (category == null)
            {
                return Json(new { success = false, message = "Error when deleting" });
            }
            else
            {
                _unitOfWork.Category.Remove(category);
                _unitOfWork.Save();
                return Json(new { success = true, message = "Delete successful" });
            }
        }
        #endregion
    }
}

dotnet-core/Bulky/BulkyWeb/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Bulky.DataAccess.IRepository;
using Microsoft.AspNetCore.Mvc.Rendering;
using Bulky.Models.ViewModels;
using NuGet.Packaging.Signing;
using Bulky.Models;
using Stripe;

namespace BulkyWeb.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostEnvironment = hostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            ProductVM productVM = new()
            {
                Product = new(),
                CategoryList = _unitOfWork.Category.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
            };

            if (id != null && id != 0)
            {
                productVM.Product = _unitOfWork.Product.GetFirstOrDefaultNull(
                    u => u.Id == id, includeProps: "ProductImages");
            }
            return View(productVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM productVM, List<IFormFile>? files)
        {

            if (ModelState.IsValid)
            {
                if (productVM.Product?.Id == 0)
                {
                    _unitOfWork.Product.Add(productVM.Product);
                }
                else
                {
                    _unitOfWork.Product.Update(productVM.Product);
                }
                _unitOfWork.Save();

                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (files != null)
                {
                    foreach (IFormFile file in files)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                        string productPath = @"images/products/product-" + productVM.Product.Id;
                        string finalPath = Path.Combine(wwwRootPath, productPath);

                        if (!Directory.Exists(finalPath)) Directory.CreateDirectory(finalPath);

                        using (var fileStream = new FileStream(
                            Path.Combine(finalPath, fileName),
                            FileMode.Create))
                        {
                            file.CopyTo(fileStream);
                        }
                        ProductImage productImage = new()
                        {
                            ImageUrl = @"/" + productPath + @"/" + fileName,
                            ProductId = productVM.Product.Id
                        };

                        if (productVM.Product.ProductImages == null)
                        {
                            productVM.Product.ProductImages = new List<ProductImage>();
                        }
                        productVM.Product.ProductImages.Add(productImage);
                        _unitOfWork.ProductImage.Add(productImage);
                    }
                    _unitOfWork.Product.Update(productVM.Product);
                    _unitOfWork.Save();
                }
                TempData["success"] = "Product created/updated successfully";

                return RedirectToAction("Index");
            }
            return View(productVM);
        }

        public IActionResult DeleteImage(int imageId)
        {
            var image = _unitOfWork.ProductImage.GetFirstOrDefaultNull(i => i.Id == imageId);
            int productId = image.ProductId;
            if (image != null)
            {
                if (!String.IsNullOrEmpty(image.ImageUrl))
                {
                    var imagePath = Path.Combine(_hostEnvironment.WebRootPath, image.ImageUrl.TrimStart('/'));
                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }
                    _unitOfWork.ProductImage.Remove(image);
                    _unitOfWork.Save();
                    TempData["success"] = "Deleted successfully";
                }
            }
            return RedirectToAction(nameof(Upsert), new { id = productId });
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            var productList = _unitOfWork.Product.GetAll(includeProps: "Category,CoverType");
            return Json(new { data = productList });
        }

        [HttpDelete, ActionName("Delete")]
        public IActionResult ApiDelete(int? id)
        {
            var product = _unitOfWork.Product.GetFirstOrDefaultNull(p => p.Id == id);
            if (product == null)
            {
                return Json(new { success = false, message = "Error when deleting" });
            }
            else
            {
                string productPath = @"images/products/product-" + id;
                string finalPath = Path.Combine(_hostEnvironment.WebRootPath, productPath);
                if (Directory.Exists(finalPath))
                {
                    string[] filePaths = Directory.GetFiles(finalPath);
                    foreach (var filePath in filePaths)
                    {
                        System.IO.File.Delete(filePath);
                    }
                    Directory.Delete(finalPath);
                }
                _unitOfWork.Product.Remove(product);
                _unitOfWork.Save();
            }
            return Json(new { success = true, message = "Delete successful" });
        }

        #endregion
    }
}

dotnet-core/Bulky/BulkyWeb/Areas/Admin/Controllers/UserController.cs
using Bulky.DataAccess;
using Bulky.DataAccess.Repository;
using Bulky.DataAccess.IRepository;
using Bulky.Models;
using Bulky.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Bulky.Utility;
using Microsoft.AspNetCore.Identity;

namespace BulkyBookWeb.Controllers;
[Area("Admin")]
public class UserController : Controller
{
    //private readonly ApplicationDbContext _db;
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly UserManager<IdentityUser> _userManager;
    private readonly IUnitOfWork _unitOfWork;

    public UserController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
    {
        _unitOfWork = unitOfWork;
        _userManager = userManager;
        _roleManager = roleManager;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult RoleManagement(string userId)
    {
        RoleManagementVM RoleVM = new RoleManagementVM()
        {
            ApplicationUser = _unitOfWork.ApplicationUser
                .GetFirstOrDefaultNull(u => u.Id == userId, includeProps: "Company"),
            RoleList = _roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Name
            }),
            CompanyList = _unitOfWork.Company.GetAll().Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()
            })
        };
        RoleVM.ApplicationUser.Role = _userManager.GetRolesAsync(
            _unitOfWork.ApplicationUser.GetFirstOrDefaultNull(u => u.Id == userId)
        ).GetAwaiter().GetResult().FirstOrDefault();
        return View(RoleVM);
    }

    [HttpPost]
    public IActionResult RoleManagement(RoleManagementVM roleVM)
    {
        string oldRole = _userManager.GetRolesAsync(
            _unitOfWork.ApplicationUser.GetFirstOrDefaultNull(u => u.Id == roleVM.ApplicationUser.Id)
        ).GetAwaiter().GetResult().FirstOrDefault();
        ApplicationUser applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefaultNull(u => u.Id == roleVM.ApplicationUser.Id);
        
        if (roleVM.ApplicationUser.Role != oldRole)
        {
            if (roleVM.ApplicationUser.Role == SD.RoleUserComp)
            {
                applicationUser.CompanyId = roleVM.ApplicationUser.CompanyId;
            }
            if (oldRole == SD.RoleUserComp)
            {
                applicationUser.CompanyId = null;
            }
            _unitOfWork.ApplicationUser.Update(applicationUser);
            _unitOfWork.Save();
            _userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
            _userManager.AddToRoleAsync(applicationUser, roleVM.ApplicationUser.Role).GetAwaiter().GetResult();
        }
        else
        {
            if (oldRole == SD.RoleUserComp && applicationUser.CompanyId != roleVM.ApplicationUser.CompanyId)
            {
                applicationUser.CompanyId = roleVM.ApplicationUser.CompanyId;
                _unitOfWork.ApplicationUser.Update(applicationUser);
                _unitOfWork.Save();
            }
        }
        return RedirectToAction("Index");
    }

    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        List<ApplicationUser> users = _unitOfWork.ApplicationUser.GetAll(includeProps: "Company").ToList();

        foreach (var user in users)
        {
            user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();
            if (user.Company == null)
            {
                user.Company = new Company { Name = "" };
            }
        }
        return Json(new { data = users });
    }

    [HttpPost]
    public IActionResult LockUnlock([FromBody] string id)
    {
        var user = _unitOfWork.ApplicationUser.GetFirstOrDefaultNull(u => u.Id == id);
        if (user == null)
        {
            return Json(new { success = false, message = "Error when locking/unlocking" });
        }
        if (user.LockoutEnd != null && user.LockoutEnd > DateTime.Now)
        {
            user.LockoutEnd = DateTime.Now;
        }
        else
        {
            user.LockoutEnd = DateTime.Now.AddYears(1000);
        }
        _unitOfWork.ApplicationUser.Update(user);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Locking/Unlocking success" });
    }
    #endregion
}

dotnet-core/Bulky/BulkyWeb/ViewComponents/ShoppingCartViewComponent.cs
using System;
using System.Security.Claims;
using Bulky.DataAccess.IRepository;
using Bulky.Utility;
using Microsoft.AspNetCore.Mvc;

namespace Bulky.ViewComponents
{
	public class ShoppingCartViewComponent : ViewComponent
	{
		private readonly IUnitOfWork unitOfWork;

		public ShoppingCartViewComponent(IUnitOfWork _unitOfWork)
		{
			unitOfWork = _unitOfWork;
		}

		public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity) User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			if (claim != null)
			{
				if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
				{
					return View(HttpContext.Session.GetInt32(SD.SessionCart));
				}
				else
				{
					HttpContext.Session.SetInt32(
						SD.SessionCart,
						unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value).ToList().Count);
                    return View(HttpContext.Session.GetInt32(SD.SessionCart));
                }
			}
			else
			{
				HttpContext.Session.Clear();
				return View(0);
			}
        }
	}
}

dotnet-core/Bulky/BulkyWeb/Views/Shared/_Layout.cshtml
@using Bulky.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/BulkyWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">BulkyWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(SD.RoleAdmin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">CMS</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create user</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Order" asp-action="Index" class="nav-link">
                                Manage orders
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container text-center">
            &copy; 2023 - BulkyWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

dotnet-core/Bulky/BulkyWeb/Views/Shared/_Notification.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

@if (TempData["success"] != null)
{
    <script>
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script>
        toastr.error('@TempData["error"]');
    </script>
}